### ISSUE TITLE
[Question] where is the child process

### ISSUE THREAD

**Issue by zjhmale** [alanz/haskell-lsp#1]
Hi @alanz, as a usual way, there is always a child process to communicate with an executable which in this language server it should be `haskell-ide-engine`, but after walking throught the code, i can not find any part of it, so how does this language server actually interact with `haskell-ide-engine`? am i missing something here? thx in advance!

**Comment by alanz** [comment]
Hi. A good question.

At the moment, the main loop is invoked by the main thread in hie, via the "--lsp" flag, which comes out here: https://github.com/alanz/haskell-ide-engine/blob/lsp/app/MainHie.hs#L167

This in turn eventually calls the badly named "wait" in https://github.com/alanz/haskell-lsp/blob/master/src/Language/Haskell/LSP/Control.hs#L56

I have actually renamed that to "ioLoop" in my current (unpushed) branch, because it is confusing.

That said, I am still considering the control model, as it effectively needs to mediate between two async processes, the stdio transport for LSP and the dispatcher in hie. I am strongly considering a model something like an erlang gen_server, where everything gets fed into a single channel and processed sequentially against a common state, which can be used to tie up LSP requests with hie responses, and generate async notifications as required.

**Comment by alanz** [comment]
BTW, I see you have a gluon language server. The intent behind haskell-lsp is that it provides plumbing for language servers implemented in haskell, without the specifics. Hence it is a separate repo to hie.

I would love to see it getting use elsewhere, and any pull requests / design input from that.

**Comment by zjhmale** [comment]
@alanz thx for the explanation! now i know the things under the hood, i did not notice the JSON RPC sorry. 😅 

yeah, maybe we can take this as a starting point to fix https://github.com/commercialhaskell/intero/issues/274 where i originally saw the link of this repo :)
>I would love to see it getting use elsewhere, and any pull requests / design input from that.
